In [9]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

In [17]:
from keras.preprocessing import image
model = load_model('detect_new_model.h5')

In [18]:
face_cascade = cv2.CascadeClassifier('Pictures/haarcascade_frontalface_default.xml')

def face_extractor(img):    
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-18-9fff88f8d843>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [26]:
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        
        img_array = np.array(im)
                    
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.99):
            name='Pranav'
        else:
            name='Sreedevi'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[9.9999714e-01 2.8386405e-06]]
[[1.0000000e+00 5.6836438e-34]]
[[1.000000e+00 7.754052e-12]]
[[1.0000000e+00 1.5992826e-22]]
[[1.000000e+00 4.876601e-25]]
[[1.0000000e+00 4.4300324e-23]]
[[1.0000000e+00 5.0970354e-36]]
[[1.0000000e+00 6.2519913e-32]]
[[1. 0.]]
[[1.0000000e+00 1.7301522e-24]]
[[1.0000000e+00 1.7955066e-26]]
[[1.0000000e+00 9.0678945e-27]]
[[1.0000000e+00 3.7541733e-23]]
[[1.0000000e+00 5.6326266e-24]]
[[1.0000000e+00 1.9436533e-31]]
[[1.000000e+00 4.173403e-34]]
[[1.0000000e+00 2.2270815e-33]]
[[1.00000e+00 6.90545e-17]]
[[1.0000000e+00 8.4638724e-38]]
[[1.0000000e+00 1.5009437e-29]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
